apiVersion: compliance.openshift.io/v1alpha1
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    name: rhcos4-moderate
    kind: Profile
  - apiGroup: compliance.openshift.io/v1alpha1
    name: ocp4-cis
    kind: Profile 
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  name: default
  #name: default-auto-apply
  kind: ScanSetting
kind: ScanSettingBinding
metadata:
  name: cis-and-moderate-profile
  namespace: openshift-compliance
