apiVersion: maistra.io/v2
# Istio 1.6.5
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  version: v2.0
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    openshiftRoute:
      enabled: true
    ingress:
        enabled: true
        ingress: false
        runtime:
          container:
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 1
                memory: 1Gi
          deployment:
            autoScaling:
              maxReplicas: 4
              minReplicas: 3
              targetCPUUtilizationPercentage: 85
              enabled: true
            pod:
              tolerations:
              - key: node.kubernetes.io/unreachable
                operator: Exists
                effect: NoExecute
                tolerationSeconds: 60
        service:
          type: ClusterIP
    egress:
        enabled: false
  general:
    logging:
      componentLevels:
        default: info
      logAsJSON: false
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  runtime:
    components:
      prometheus:                   
        deployment:
          replicas: 2
        podDisruption:
          enabled: true
          minAvailable: 1
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60        
      pilot:
        deployment:
          replicas: 2
        pod:
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoExecute
            tolerationSeconds: 60
    defaults:
      deployment:
        podDisruption:
          enabled: true
          minAvailable: 1
  telemetry:
    type: Istiod
  proxy:
    accessLogging:
      envoyService:
        enabled: false
      file:
        encoding: TEXT
        name: /dev/stdout