apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-app-alert
  namespace: project1
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
spec:
  groups:
  - name: backend-app
    rules:
    - alert: ConcurrentBackend
      expr: sum(application_com_example_quarkus_BackendResource_concurrentBackend_current)>15
      # wait just 1 minute for demo purpose
      for: 1m
      labels:
        severity: 'warning'
      annotations:
        message: 'Total concurrent request is {{ $value }} request/sec'
    - alert: HighLatency
      expr: application_com_example_quarkus_BackendResource_timeBackend_max_seconds>5
      labels:
        severity: 'critical'
      annotations:
        message: '{{ $labels.instance }} response time is {{ $value }} sec'