apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: manifests/apps-kustomize/overlays/dev
    repoURL: https://github.com/rhthsa/openshift-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
